name: Build and Deploy App

env:
  PYTHON_VERSION: '3.10'              # set this to the Python version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy-dev:
    name: Deploy App to Development
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          
  deploy-qa:
      name: Deploy App to QA
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: deploy-dev
      environment:
        name: 'QA'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: python-app
            path: .
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ vars.AZURE_WEBAPP_NAME }}

  deploy-staging:
      name: Deploy App to Staging
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: deploy-qa
      environment:
        name: 'Staging'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: python-app
            path: .
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ vars.AZURE_WEBAPP_NAME }}
            slot-name: "${{ vars.SLOT_NAME }}"
            
  release-to-prod:
    name: Release to Production
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: 'Staging-Production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Swap slots
      run: az webapp deployment slot swap --slot staging --target-slot production -n ${{ vars.AZURE_WEBAPP_NAME }} -g ${{ vars.RESOURCE_GROUP_NAME }}
