name: Deploy Infrastructure

on: 
   workflow_dispatch:
    inputs:
      Environment:
        description: 'Log level'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - QA
          - Staging-Production

jobs:
  Deploy:
    name: Deploy ${{ github.event.inputs.Environment }} Environment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Environment }}
    steps:
      - name: Script Debug
        run: |
         echo  ${{ vars.RESOURCE_GROUP_NAME }} \
         echo  ${{ github.event.inputs.Environment }} \
         
      - name: Checkout
        uses: actions/checkout@v4.0.0
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                  
      - name: Deploy Services with Bicep
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: subscription
          region: ${{ vars.RESOURCE_GROUP_LOCATION }}
          subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
          resourceGroupName: ${{vars.RESOURCE_GROUP_NAME}}
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Incremental
          template: infra/demo/main.bicep
          parameters: resourceGroupName=${{ vars.RESOURCE_GROUP_NAME }} environmentName=${{ github.event.inputs.Environment }} searchServiceKey=${{secrets.SEARCH_SERVICE_KEY}} openAiKey=${{secrets.OPEN_AI_KEY}} authClientSecret=${{secrets.AUTH_CLIENT_SECRET}} authClientId=${{vars.AUTH_CLIENT_ID}}

  
