name: Deploy Infrastructure

on: 
   workflow_dispatch:
    inputs:
      Environment:
        description: 'Log level'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - QA
          - Production

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Script Debug
        run: |
         echo  ${{ vars.RESOURCE_GROUP_NAME }} \
         
      - name: Checkout
        uses: actions/checkout@v4.0.0
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"

  
